import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import type { PropsWithChildren } from "react";
import type { Component } from "@/components/utils/component";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Movies",
  description: "Generated by create next app"
};

export const RootLayout: Component<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body className={cn(
        "bg-slate-50 dark:bg-blue-900",
        GeistSans.className
      )}>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;